"""Generate every data table of the paper straight from the measurement files.

Nothing in ``paper/tables/*.tex`` is typed by hand: each file is produced here
from one of

  * ``validate_pytrace.json``   -- the V1..V5 verification suite (pytrace.py)
  * ``audit_nt.json``           -- the Novikov-Thorne / Page-Thorne audit
  * ``render_benchmark.json``   -- the Chromium timing sweep (f22)
  * ``../web/src/main.js``      -- the shipped parameter defaults
  * ``audit_nt.py``             -- recomputed cumulative energy profiles

Run ``python tools/make_tables.py`` after re-running any of those tools; the
paper only ever inputs the generated files, so a figure or table update can
never silently disagree with the text.
"""
import json
import os
import re
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
OUT = os.path.join(os.path.dirname(HERE), "tables")

sys.path.insert(0, HERE)
import audit_nt as A                                           # noqa: E402


# --------------------------------------------------------------------------- #
# formatting helpers                                                          #
# --------------------------------------------------------------------------- #
def jload(name):
    with open(os.path.join(HERE, name), encoding="utf-8") as fh:
        return json.load(fh)


def sciraw(x, d=3):
    """Scientific notation body (no math delimiters) with ``d`` digits."""
    if x == 0:
        return "0"
    e = int(np.floor(np.log10(abs(x))))
    m = x / 10.0 ** e
    if m >= 10.0:
        m /= 10.0
        e += 1
    if m < 1.0:
        m *= 10.0
        e -= 1
    return "%.*f\\times 10^{%d}" % (d, m, e)


def sci(x, d=3):
    """LaTeX scientific notation; wraps :func:`sciraw` in math mode."""
    return "$%s$" % sciraw(x, d)


def rel(x, d=2):
    return "$%+.*f\\%%$" % (d, 100.0 * x)


def num(x, d=3):
    return "%.*f" % (d, x)


def px(x, d=2):
    """Signed pixel offset, or an em-dash when the local frame is degenerate."""
    if x is None:
        return "--"
    return "$%+.*f$" % (d, x)


_SUP = {
    "\u2070": "0", "\u00b9": "1", "\u00b2": "2", "\u00b3": "3", "\u2074": "4",
    "\u2075": "5", "\u2076": "6", "\u2077": "7", "\u2078": "8", "\u2079": "9",
    "\u207a": "+", "\u207b": "-",
}


def texify(s):
    """Rewrite literal superscripts into math superscripts for the PDF body.

    Preset names are shown verbatim in the application UI (``T=10\u2077 K``), but the
    text fonts used by the paper have no U+2077 glyph, so the table build turns
    any run of superscript characters into ``$^{7}$``.  Without this the
    compiler only warns and silently drops the character from the table.
    """
    out, buf = [], []
    for ch in s:
        if ch in _SUP:
            buf.append(_SUP[ch])
            continue
        if buf:
            out.append("$^{%s}$" % "".join(buf))
            buf = []
        out.append(ch)
    if buf:
        out.append("$^{%s}$" % "".join(buf))
    return "".join(out)


def w(name, body, caption, label, cols, head, size="\\small",
      align=None, extra=""):
    align = align or ("l" + "r" * (len(head) - 1))
    lines = [
        "%% generated by tools/make_tables.py -- do not edit",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{%s}" % caption,
        "\\label{%s}" % label,
        size,
        "\\begin{tabular}{%s}" % align,
        "\\toprule",
        " & ".join(head) + " \\\\",
        "\\midrule",
    ]
    lines += body
    lines += ["\\bottomrule", "\\end{tabular}", extra, "\\end{table}", ""]
    path = os.path.join(OUT, name)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines))
    print("[tbl] %-26s %3d rows" % (name, len(body)))
    return path


# --------------------------------------------------------------------------- #
# V1..V5                                                                      #
# --------------------------------------------------------------------------- #
def t_validate():
    d = jload("validate_pytrace.json")
    b_c = d["V1"][0]["b_crit"]

    body = []
    for r in d["V1"]:
        body.append("%.0e & %.12f & %s \\\\"
                    % (r["tol"], r["b_edge"], sci(abs(r["rel"]), 2)))
    w("t01_validate_v1.tex", body,
      "V1：临界冲击参数的收敛。\\texttt{pytrace.py} 对每条光线以 $y$ 为参数"
      "用二分法定位视界掠射边缘，$b_{c}=3\\sqrt{3}\\,M=%.12f$；"
      "偏差按 $|b_{\\rm edge}-b_{c}|/b_{c}$ 计。" % b_c,
      "tab:v1", 3, ["容差 $tol$", "$b_{\\rm edge}$", "相对偏差"])

    body = []
    for r in d["V2"]:
        body.append("%.0e & %d & %s & %s & %.4f & %.2f \\\\"
                    % (r["tol"], r["samples"], sci(r["max_resid"], 2),
                       sci(r["mean_resid"], 2), r["r_min_M"], r["phi_span"]))
    s = d["V2_summary"]
    w("t02_validate_v2.tex", body,
      "V2：近临界轨道（$b=%.9f$，绕光子球 $%.2f$\\,rad）的积分守恒性。"
      "$r_{\\min}$ 为该光线的最近距离；$\\phi_{\\rm span}$ 为总方位角。"
      "容差从 $10^{-2}$ 收紧到 $10^{-4}$ 时最大残差下降约 $%.0f$ 倍，"
      "并在 $tol=%s$ 处触底于 $%s$。"
      % (d["V2"][0]["b"], d["V2"][0]["phi_span"], s["max_ratio"],
         sciraw(s["plateau_tol"], 0), sciraw(s["plateau_max"], 2)),
      "tab:v2", 6, ["容差 $tol$", "采样点", "$\\max$ 残差",
                    "$\\overline{\\rm res}$", "$r_{\\min}/M$",
                    "$\\phi_{\\rm span}$ [rad]"])

    body = []
    for r in d["V3"]:
        body.append("%d$\\times$%d & %.3f & %.4f & %s & %.4f & %s \\\\"
                    % (r["nx"], r["ny"], r["measured_px"], r["analytic_px"],
                       sci(abs(r["rel"]), 2), r["refined_px"],
                       sci(abs(r["rel_refined"]), 2)))
    w("t03_shadow_pixels.tex", body,
      "V3：阴影半径的像素级一致性。``scan`` 为整数像素扫描的边缘，"
      "``sub-px`` 为在其上抛物拟合反解得到的亚像素边缘，"
      "``closed`` 为闭式 $R_{\\rm px}=f_{\\rm px}\\tan\\psi_{\\rm sh}$，"
      "$f_{\\rm px}=(H/2)/\\tan(\\mathrm{fov}/2)$。亚像素口径与闭式相符到 "
      "%s 量级。" % sci(abs(d["V3"][2]["rel_refined"]), 1),
      "tab:v3", 6, ["分辨率", "扫描 [px]", "闭式 [px]", "扫描偏差",
                    "亚像素 [px]", "亚像素偏差"])

    body = []
    for r in d["V4a"]:
        body.append("%.4f & %.8f & %.8f & %s & %.6f \\\\"
                    % (r["y"], r["b_tracer"], r["b_analytic"],
                       sci(abs(r["rel_b"]), 2), r["psi_tracer_deg"]))
    w("t04_impact.tex", body,
      "V4a：从屏幕坐标到冲击参数。给定像面纵坐标 $y$（视场半高归一化），"
      "几何上 $b=y\\,r_{0}\\,f_{\\rm obs}/\\sqrt{1-y^{2}}$；"
      "``tracer`` 为着色器内同一量的数值实现，``analytic`` 为闭式，"
      "两者相符到双精度舍入水平。",
      "tab:v4a", 5, ["$y$", "$b$ (tracer)", "$b$ (解析)", "相对偏差",
                     "$\\psi$ [deg]"])

    body = []
    for r in d["V4b"]:
        body.append("%.1f & %.6f & %.6f & %.6f & %s & %s & %s & %s \\\\"
                    % (r["r0"], r["psi_deg"], r["flat_deg"], r["chart_deg"],
                       rel(r["err_flat"]), rel(r["err_chart"]),
                       px(r["px_flat"]), px(r["px_chart"])))
    w("t05_frame.tex", body,
      "V4b：阴影角半径与观测口径的关系（$M=1$）。``FIDO`` 为静态观测者局部"
      "正交标架中的真实角半径，$\\sin\\psi=(3\\sqrt{3}M/r_{0})"
      "\\sqrt{1-2M/r_{0}}$；``flat`` 为把同一冲击参数按平直空间关系 "
      "$\\psi=\\arcsin(b/r_{0})$ 换算的角度，``chart`` 为施瓦西坐标角。"
      "末两列是以 $1000\\times600$、$\\mathrm{fov}=58^{\\circ}$ 计的像素量。",
      "tab:v4b", 8, ["$r_{0}/M$", "$\\psi_{\\rm FIDO}$ [deg]",
                     "$\\psi_{\\rm flat}$ [deg]", "$\\psi_{\\rm chart}$ [deg]",
                     "flat 偏差", "chart 偏差", "$\\Delta$px (flat)",
                     "$\\Delta$px (chart)"])

    body = []
    for r in d["V5"]["rows"]:
        body.append("%.4f & %s & %.5f \\\\"
                    % (r["b"], sci(r["err_rad"], 3), r["err_px_1000x600"]))
    w("t06_escape.tex", body,
      "V5：有限逃逸半径 $R_{\\rm esc}=%.0f\\,M$ 造成的出射方向误差"
      "（$1000\\times600$、$\\mathrm{fov}=58^{\\circ}$ 下的像素量）。"
      "最大误差 $%.3f$\\,px，远小于一个像素。"
      % (d["V5"]["R_esc"], d["V5"]["max_err_px"]),
      "tab:v5", 3, ["$b/M$", "方向误差 [rad]", "像素误差"])


# --------------------------------------------------------------------------- #
# accretion disc                                                              #
# --------------------------------------------------------------------------- #
def t_disk():
    a = jload("audit_nt.json")
    p = a["peaks"]

    body = []
    for r in a["B_check"]:
        body.append("%.2f & %.10f & %.10f & %s & %s \\\\"
                    % (r["r"], r["quadrature"], r["closed_minus"],
                       sci(abs(r["rel_err_minus"]), 2),
                       sci(abs(r["rel_err_plus"]), 2)))
    w("t07_torque_integral.tex", body,
      "扭矩积分 $B(r)=\\int_{r_{\\rm in}}^{r}(E-\\Omega L)\\,\\mathrm{d}L$ 的"
      "独立核算。``quad`` 为 $4\\times10^{6}$ 格点中值积分，``closed`` 为本文"
      "采用的闭式，``plus`` 为文献中偶见的符号变体；闭式与积分相符到 "
      "$10^{-14}$ 的相对量级，符号变体则偏离 $10^{-1}$--$10^{1}$。",
      "tab:bcheck", 5, ["$r/M$", "$B$ (quad)", "$B$ (closed)",
                        "$\\Delta_{\\rm closed}$", "$\\Delta_{\\rm plus}$"])

    want = ["E(r)", "1 (coordinate area)", "(1-2/r)^-1/2 (proper area)",
            "(1-2/r)^+1/2", "(1-3/r)^+1/2", "(1-3/r)^-1/2", "(1-3/r)^+1",
            "(1-3/r)^-1", "(1-3/r)^+3/2", "(1-3/r)^-3/2",
            "(1-2/r)^-1/2 (1-3/r)^1/2 [comoving dtau]",
            "E(r) (1-2/r)^-1/2", "P'(r) torque identity"]
    show = {"1 (coordinate area)": "$1$\\ (坐标面积)",
            "E(r)": "$E(r)$\\ (谱移不变量)",
            "(1-2/r)^-1/2 (proper area)": "$(1-2/r)^{-1/2}$",
            "(1-2/r)^+1/2": "$(1-2/r)^{+1/2}$",
            "(1-3/r)^+1/2": "$(1-3/r)^{+1/2}$",
            "(1-3/r)^-1/2": "$(1-3/r)^{-1/2}$",
            "(1-3/r)^+1": "$(1-3/r)^{+1}$",
            "(1-3/r)^-1": "$(1-3/r)^{-1}$",
            "(1-3/r)^+3/2": "$(1-3/r)^{+3/2}$",
            "(1-3/r)^-3/2": "$(1-3/r)^{-3/2}$",
            "(1-2/r)^-1/2 (1-3/r)^1/2 [comoving dtau]":
                "$(1-2/r)^{-1/2}(1-3/r)^{1/2}$",
            "E(r) (1-2/r)^-1/2": "$E(r)(1-2/r)^{-1/2}$",
            "P'(r) torque identity": "$-(L-L_{\\rm in})"
                                     "\\,\\mathrm{d}\\Omega/\\mathrm{d}r$"}
    body = []
    for key in want:
        if key not in a["sum_rule_NT"]:
            continue
        val = a["sum_rule_NT"][key]
        tag = "\\textbf{%.6f}" % val if abs(val - 1.0) < 1e-6 else "%.6f" % val
        ok = "$\\checkmark$" if abs(val - 1.0) < 1e-6 else "$\\times$"
        body.append("%s & %s & %s \\\\" % (show.get(key, key), tag, ok))
    body.append("\\midrule")
    body.append("SS 对照：$\\eta_{\\rm SS}=1/12$，$w=1$ & %.6f & $\\checkmark$ \\\\"
                % a["SS_control"]["weight_unity"])
    w("t08_sumrule.tex", body,
      "求和规则 $\\int 2\\pi r\\,4F(r)\\,w(r)\\,\\mathrm{d}r/\\eta$ 在不同权重下的"
      "取值（$\\eta=1-E(r_{\\rm in})=%.6f$，$4\\times10^{6}$ 格点，$M=1$、"
      "$r_{\\rm in}=6M$）。只有 $w=E(r)$ 使积分等于 $1$。" % a["eta"],
      "tab:sumrule", 3, ["权重 $w(r)$", "积分$/\\eta$", "是否 $=1$"])

    body = []
    for r in a["flux_table"]:
        body.append("%.4f & %s & %s & %.4f \\\\"
                    % (r["r"], sci(r["NT"], 3), sci(r["SS"], 3),
                       r["NT_over_SS"]))
    w("t09_flux.tex", body,
      "归一化通量剖面（$\\dot M=1$、$r_{\\rm in}=6M$、$M=1$）。"
      "Page--Thorne（PT）与 Shakura--Sunyaev（SS）在 $r\\to\\infty$ 一致，"
      "在峰值区相差 $3$ 倍以上；峰值半径分别为 "
      "$r_{\\rm peak}^{\\rm PT}=%.6f\\,M=%.6f\\,r_{\\rm in}$ 与 "
      "$r_{\\rm peak}^{\\rm SS}=%.6f\\,M=%.6f\\,r_{\\rm in}$。"
      % (p["r_peak_NT_M"], p["r_peak_NT_over_r_in"], p["r_peak_SS_M"],
         p["r_peak_SS_over_r_in"]),
      "tab:flux", 4, ["$r/M$", "$F_{\\rm PT}$", "$F_{\\rm SS}$",
                      "$F_{\\rm PT}/F_{\\rm SS}$"])

    n = 4_000_001
    i = np.arange(n, dtype=float) + 0.5
    x = i / n
    r = A.R_IN / (1.0 - x)
    drdx = A.R_IN / (1.0 - x) ** 2
    eta = a["eta"]
    with np.errstate(divide="ignore", invalid="ignore"):
        flux = A.flux_nt(r)
        pp = A.Pprime(r)
    dE = 4.0 * np.pi * r * flux * A.energy(r) * drdx / n
    dP = pp * drdx / n
    cumE = np.cumsum(dE) / eta
    cumP = np.cumsum(dP) / eta
    marks = [6.5, 7.0, 8.0, 10.0, 12.0, 16.0, 26.0, 50.0, 100.0, 300.0,
             1.0e3, 1.0e4, 1.0e6]
    body = []
    for rq in marks:
        k = min(max(int(np.searchsorted(r, rq)), 0), n - 1)
        ratio = ((4.0 * np.pi * r[k] * flux[k] * A.energy(r[k])) / pp[k]
                 if pp[k] > 0 else float("nan"))
        body.append("%-7s & %.6f & %.6f & %.4f \\\\"
                    % (("%g" % rq), cumE[k], cumP[k], ratio))
    w("t10_cumulative.tex", body,
      "累积辐射功率（$M=1$，$r_{\\rm in}=6M$，$4\\times10^{6}$ 格点）。"
      "``$L(r)$`` 为 $\\int 4\\pi r' F E\\,\\mathrm{d}r'/\\eta$，"
      "``$P(r)$`` 为扭矩恒等式的同一量。两者逐点可差 $20\\%$（末列），"
      "但积分都收敛到 $1$：求和规则是整体守恒律，不是逐点等式。",
      "tab:cumulative", 4, ["$r/M$", "$L(r)/\\dot M c^{2}$",
                            "$P(r)/\\dot M c^{2}$", "$4\\pi rFE/P'$"])


# --------------------------------------------------------------------------- #
# renderer performance                                                        #
# --------------------------------------------------------------------------- #
def t_perf():
    d = jload("render_benchmark.json")["rows"]

    def emit(kind, name, label, caption, xcol, xhead):
        sub = [r for r in d if r["kind"] == kind]
        sub.sort(key=lambda r: (r["scale"], r[xcol]))
        body = []
        for r in sub:
            ms = float(r["t_min"])
            body.append("%.2f & %s & %.4f & %d$\\times$%d & %.1f & %.2f \\\\"
                        % (r["scale"], xhead % r[xcol], r["tol"], r["traced_w"],
                           r["traced_h"], ms, 1000.0 / ms))
        w(name, body, caption, label, 6,
          ["视口缩放 $s$", "参数", "$tol$", "追踪像素", "$T$ [ms]",
           "等效 fps"])

    emit("steps", "t11_perf_steps.tex", "tab:perfsteps",
         "步数上限扫描（$tol=0.03$，窗口 $1000\\times600$、侧栏收起、"
         "\\texttt{autoQuality=false}）。$T$ 为把一帧渲染进离屏目标并强制回读的"
         "$7$ 次同步墙钟最小值。$n_{\\max}\\geq300$ 后耗时趋平：多数光线在预算内"
         "已提前逃逸或落入视界，继续抬高预算不再增加实际执行步数。",
         "steps", "%d")

    emit("tol", "t12_perf_tol.tex", "tab:perftol",
         "容差扫描（$n_{\\max}=4096$）。自适应步长 $h\\propto tol\\,u/|\\mathrm{d}u|$，"
         "固定轨迹所需步数 $\\propto 1/tol^{p}$，实测 $p=0.91$。"
         "$tol=0.0075$ 的四组已被 $n_{\\max}=4096$ 截断（工作不再随容差增长），"
         "其耗时是预算下界而非容差律的外推，故单列于此，并在正文图"
         "$\\ref{fig:22}$ 的 (d) 面板中标记。",
         "tol", "%.4f")


# --------------------------------------------------------------------------- #
# shipped parameter defaults and presets                                      #
# --------------------------------------------------------------------------- #
DEFAULT_MEANING = {
    "dist": ("$r_0$", "相机静止观测者到黑洞的坐标半径", "M", "26"),
    "elevation": ("$i$", "视线相对赤道盘的仰角", "deg", "13"),
    "fov": ("$\\theta_{\\rm fov}$", "垂直视场角", "deg", "58"),
    "autoRotate": ("--", "相机自动环绕（OrbitControls.autoRotate）", "--",
                   "false"),
    "showDisk": ("$\\delta_{\\rm d}$", "吸积盘开关", "--", "1"),
    "diskInner": ("$r_{\\rm in}$", "吸积盘内边缘（ISCO）", "M", "6"),
    "diskOuter": ("$r_{\\rm out}$", "吸积盘外边缘", "M", "26"),
    "diskThick": ("$H/R$", "盘几何半厚与半径之比", "--", "0.075"),
    "diskTemp": ("$T_{\\rm pk}$", "通量峰值处的黑体温度（色温标定；$T=T_{\\rm pk}F^{1/4}$）", "K",
                 "9000"),
    "diskBright": ("$\\mathcal{B}$", "发射强度整体增益", "--", "1"),
    "diskOpacity": ("$\\kappa\\Sigma_0$", "径向光学厚度标度（吸收+发射）", "--",
                    "2.6"),
    "turb": ("$\\delta_{\\rm t}$", "局域湍流密度扰动幅度", "--", "0.55"),
    "spin": ("$s$", "开普勒角速度符号/方向", "--", "1"),
    "kepler": ("$\\Omega_{\\rm K}$", "开普勒角速度整体因子", "--", "1"),
    "doppler": ("$\\mathcal{D}$", "相对论频移（多普勒+引力）开关增益", "--", "1"),
    "fluxModel": ("$\\mathcal{F}$", "通量模型：1=Page-Thorne(1974)，"
                  "0=Shakura-Sunyaev(1973)", "--", "1"),
    "colorMode": ("--", "0=黑体配色，1=X 射线伪彩", "--", "0"),
    "dispTMin": ("$T_{\\rm d,min}$", "显示色标下限（伪彩模式）", "K", "2000"),
    "dispTMax": ("$T_{\\rm d,max}$", "显示色标上限（伪彩模式）", "K", "14000"),
    "showStars": ("$\\delta_{\\rm s}$", "背景星场开关", "--", "1"),
    "starBright": ("$B_{\\rm s}$", "星场亮度增益", "--", "1"),
    "maxSteps": ("$n_{\\max}$", "每条光线的 RK4 步数上限", "--", "300"),
    "tol": ("$tol$", "自适应步长的相对容差", "--", "0.03"),
    "stepScale": ("$\\sigma_h$", "自适应步长整体缩放", "--", "1"),
    "escapeR": ("$R_{\\rm esc}$", "光线判定为逃逸的外半径", "M", "140"),
    "timeRate": ("$\\dot t$", "模拟时间流速（$M$ 每秒）", "M/s", "9"),
    "paused": ("--", "时间冻结开关", "--", "false"),
    "debugMask": ("--", "调试视图掩码（阴影测量用）", "--", "0"),
    "autoQuality": ("--", "自动降采样保帧率", "--", "true"),
    "renderScale": ("$s_r$", "内部分辨率相对视口的比例", "--", "1"),
    "exposure": ("$E$", "曝光增益", "--", "1"),
    "bloom": ("$\\beta_{\\rm b}$", "泛光强度", "--", "0.35"),
    "bloomThreshold": ("$\\tau_{\\rm b}$", "泛光亮度阈值", "--", "1.6"),
    "vignette": ("$\\beta_{\\rm v}$", "暗角强度", "--", "0.35"),
    "grain": ("$\\epsilon_{\\rm g}$", "盐粒噪声幅度", "--", "0.01"),
    "accumulate": ("--", "多帧累积（静帧抗噪）", "--", "true"),
    "shadowCircle": ("--", "叠加解析阴影半径圆", "--", "false"),
}


def _read_js(relpath):
    with open(os.path.join(ROOT, relpath), encoding="utf-8") as fh:
        return fh.read()


def _block(src, name):
    m = re.search(r"const %s\s*=\s*\{(.*?)\n\};" % name, src, re.S)
    if not m:
        raise RuntimeError("cannot locate const %s in main.js" % name)
    return m.group(1)


def _pairs(block):
    """Parse a JS object-literal body into a ``{key: "literal"}`` dict.

    ``//`` comments and spread entries (``...PRESET_BASE``) carry no colon and
    are therefore skipped by the pair regex, which is exactly what the preset
    table needs: it wants the explicitly written keys of each literal only.
    """
    out = {}
    for line in block.splitlines():
        line = re.sub(r"//.*$", "", line)
        for key, value in re.findall(r"(\w+)\s*:\s*([-\w.]+)", line):
            out[key] = value
    return out


def fmt(v):
    """Format a parsed JS literal for use inside ``\\texttt{}``."""
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, str):
        return v
    if abs(v - round(v)) < 1e-12 and abs(v) < 1e5:
        return "%d" % round(v)
    if abs(v) >= 1e5:
        mantissa, exponent = ("%.1e" % v).split("e")
        return "%se%d" % (mantissa, int(exponent))
    return "%g" % v


def t_defaults():
    keys = re.findall(r"(\w+)\s*:\s*([-\w.]+)",
                      _block(_read_js("web/src/main.js"), "DEFAULTS"))
    if len(keys) != len(DEFAULT_MEANING):
        raise RuntimeError("DEFAULTS has %d keys, table documents %d"
                           % (len(keys), len(DEFAULT_MEANING)))
    body = []
    for key, value in keys:
        sym, meaning, unit, _ = DEFAULT_MEANING[key]
        body.append("%s & \\texttt{%s} & %s & %s & %s \\\\"
                    % (sym, key.replace("_", "\\_"), meaning, value, unit))
    w("t13_defaults.tex", body,
      "出厂参数默认值（\\texttt{web/src/main.js} 的 \\texttt{DEFAULTS} 对象，"
      "共 %d 个可序列化键；本表由脚本直接解析源码生成）。长度以 $M$ 为单位，"
      "角度以度为单位。" % len(keys),
      "tab:defaults", 5,
      ["符号", "程序键", "物理含义", "默认值", "单位"],
      size="\\scriptsize", align="lllrl")


def t_presets():
    js = _read_js("web/src/main.js")
    defaults = _pairs(_block(js, "DEFAULTS"))
    base = _pairs(_block(js, "PRESET_BASE"))
    src = _block(js, "PRESETS")

    def val(s):
        if s == "true":
            return True
        if s == "false":
            return False
        try:
            return float(s)
        except ValueError:
            return s

    base_v = {k: val(v) for k, v in base.items()}
    def_v = {k: val(v) for k, v in defaults.items()}
    base_diff = {k: v for k, v in base_v.items() if def_v.get(k) != v}

    body = []
    seen = 0
    for m in re.finditer(r"'([^']+)'\s*:\s*\{([^}]*)\}", src, re.S):
        name = m.group(1)
        pairs = re.findall(r"(\w+)\s*:\s*([-\w.]+)", m.group(2))
        eff = dict(base_v)
        eff.update({k: val(v) for k, v in pairs})
        delta = [(k, v) for k, v in eff.items() if def_v.get(k) != v]
        txt = ", ".join("\\texttt{%s=%s}" % (k.replace("_", "\\_"), fmt(v))
                        for k, v in delta)
        if not txt:
            txt = "--"
        body.append("%s & %s \\\\" % (texify(name), txt))
        seen += 1
    if seen != 7:
        raise RuntimeError("expected 7 presets, found %d" % seen)
    w("t14_presets.tex", body,
      "七个出厂预设的净效果。每个预设先加载公共基线 \\texttt{PRESET\\_BASE}"
      "（对全部 %d 个参数的显式赋值，其中相对 \\texttt{DEFAULTS} 仅 %s），"
      "再叠加本表所列覆盖；因此切换预设不会继承上一个预设的任何残留状态。"
      "表内只显示与 \\texttt{DEFAULTS} 不同的键，由脚本解析源码生成。"
      % (len(base_v),
         "、".join("\\texttt{%s=%s}" % (k.replace("_", "\\_"), fmt(v))
                   for k, v in sorted(base_diff.items()))),
      "tab:presets", 2, ["预设", "相对 \\texttt{DEFAULTS} 的净差异"],
      size="\\scriptsize",
      align="p{0.20\\linewidth}p{0.72\\linewidth}")


# --------------------------------------------------------------------------- #
def t_integrator():
    """Table of the integrator constants, parsed out of the shipped shader.

    Each row carries a regex that must still match ``web/src/shaders.js``;
    if a constant is renamed or retuned the table build fails loudly instead
    of silently publishing a stale number.
    """
    glsl = _read_js(os.path.join("web", "src", "shaders.js"))

    # (item, regex with the numeric literal in group 1, meaning)
    spec = [
        ("\\texttt{for (int i = 0; i < N; i++)}",
         r"for \(int i = 0; i < (\d+); i\+\+\)",
         "编译期迭代硬上限（防止病态光线挂死 GPU）"),
        ("\\texttt{uMaxSteps}",
         r"if \(i >= uMaxSteps\) break;",
         "运行期步数上限 $n_{\\max}$，用户可在 60--900 间调节"),
        ("\\texttt{u > 0.5}",
         r"if \(u > ([\d.]+)\) \{ captured = true; break; \}",
         "捕获判据：$r<\\rs$ 后不再有可能逃逸"),
        ("\\texttt{u < uMin \\&\\& du < 0}",
         r"if \(u < uMin && du < ([\d.]+)\) break;",
         "逃逸判据：向外运动且已越过 $R_{\\rm esc}$"),
        ("\\texttt{uMin = 1/max(uEscapeR, 1.6 * r0)}",
         r"float uMin = 1.0 / max\(uEscapeR, ([\d.]+) \* r0\);",
         "逃逸半径至少为观测者半径的 1.6 倍，避免相机贴视界时的伪逃逸"),
        ("\\texttt{hmax}",
         r"float hmax = ([\d.]+) - ([\d.]+) \* smoothstep\(0.0, ([\d.]+), u\);",
         "步长上界：远场 $0.35$ rad，近视界收窄到 $0.05$ rad"),
        ("\\texttt{h = uTol * u / |du|}",
         r"float h = uTol \* u / max\(abs\(du\), ([\deE.+-]+)\);",
         "把 $|\\Delta u/u|$ 限制在 $tol$ 量级（防止除零）"),
        ("\\texttt{clamp(h, 0.002, hmax)}",
         r"h = clamp\(h, ([\d.]+), hmax\) \* uStepScale;",
         "步长下界固定为 $0.002$ rad：转折点附近 $|\\dd u|\\to0$ 时不无限细分"),
        ("\\texttt{uStepScale}",
         r"\* uStepScale;",
         "全局步长缩放 $\\sigma_h$，与 $1/tol$ 近似等效（见 \\S\\ref{sec:perf}）"),
        ("\\texttt{btan < 1e-5}",
         r"if \(btan < ([\deE.+-]+)\) \{",
         "径向退化光线（$\\sin\\psi\\to0$）走解析分支，不进入积分循环"),
        ("\\texttt{int K = nearDisk ? 5 : 1}",
         r"int K = nearDisk \? (\d+) : ([\d]+);",
         "近盘段的一维子步数，用于把体积发射积到亚像素精度"),
        ("\\texttt{dtau = min(\\ldots, 6.0)}",
         r"float dtau = min\(uDiskOpacity \* rho \* dl \* avg, ([\d.]+)\);",
         "单段光学厚度上限，防止 $\\exp(-\\tau)$ 下溢导致透明度突跳"),
        ("\\texttt{trans > 0.002}",
         r"if \(uShowDisk > ([\d.]+) && trans > ([\d.]+)\)",
         "透射率截断：不透明后不再采样盘，节省算力"),
        ("\\texttt{u < 1e-6}",
         r"if \(u < ([\deE.+-]+)\) \{ u = 1e-6; break; \}",
         "数值上「跑到无穷远」的兜底退出"),
    ]

    body = []
    for label, pat, meaning in spec:
        m = re.search(pat, glsl)
        if not m:
            raise RuntimeError("integrator constant drifted: %s" % pat)
        body.append("%s & %s \\\\" % (label, meaning))

    w("t15_integrator.tex", body,
      "光测地线积分器的全部数值判据。左列为源码中的字面写法，右列为物理含义；"
      "本表由 \\texttt{tools/make\\_tables.py} 直接匹配 \\texttt{web/src/shaders.js} 的"
      "正则生成，任一常量被改动而未被本表捕获时编译脚本会立即报错。",
      "tab:integrator", 2, ["源码字面量", "作用与取值"],
      size="\\scriptsize",
      align="p{0.34\\linewidth}p{0.58\\linewidth}")


# --------------------------------------------------------------------------- #
def t_verify_summary():
    """t16: one-screen summary of the six verification experiments."""
    d = jload("validate_pytrace.json")
    v1, v2s, v3, v4a, v4b, v5 = (d["V1"], d["V2_summary"], d["V3"],
                                 d["V4a"], d["V4b"], d["V5"])
    w6 = jload("validate_accum.json")
    r2 = w6["blocks"]["r2"]
    post = w6["blocks"]["post"]
    froz = w6["blocks"]["frozen"]
    sched = np.array(r2["schedule"], dtype=float)
    rms = np.asarray(r2["rms"], dtype=float)
    hf = np.asarray(r2["hf"], dtype=float)
    sel = sched <= 1024.0
    k_rms = -np.polyfit(np.log(sched[sel]), np.log(rms[sel]), 1)[0]
    drop = rms[0] / rms[np.argmax(sched[sched <= 1024.0])]
    hf_drop = 100.0 * (1.0 - hf[np.argmax(sched[sched <= 1024.0])] / hf[0])
    hf_drop_p = 100.0 * (1.0 -
                         post["hf"][np.argmax(sched[sched <= 1024.0])]
                         / post["hf"][0])
    rep = set()
    for blk in (froz, r2, post):
        for entry in blk.get("repeat", {}).values():
            rep.update(abs(entry[k]) for k in ("rms", "rms_row", "max"))
    rep_max = max(rep) if rep else 0.0
    v5max = max(r["err_px_1000x600"] for r in v5["rows"])
    v3sub = max(abs(r["rel_refined"]) for r in v3)
    v3scan = max(abs(r["rel"]) for r in v3)
    b4 = [r for r in v4b if abs(r["r0"] - 4.0) < 1e-9][0]
    _e = int(np.floor(np.log10(v2s["plateau_tol"]) + 1e-9))
    _m = v2s["plateau_tol"] / 10.0 ** _e
    tol_tex = "%g\\times10^{%d}" % (_m, _e)

    rows = [
        ("V1",
         "临界冲击参数 $b_{c}=3\\sqrt{3}\\,M$",
         "$b_{\\rm edge}=%.12f$" % v1[-1]["b_edge"],
         sci(abs(v1[-1]["rel"]), 2),
         "$|\\Delta b|/b_{c}<10^{-12}$",
         "二分搜索在双精度舍入极限处闭合"),
        ("V2",
         "近临界轨道守恒性（$b=%.9f$，绕光子球 $%.2f$\\,rad）"
         % (d["V2"][0]["b"], d["V2"][0]["phi_span"]),
         "$\\max$ 残差 %s" % sci(v2s["plateau_max"], 2),
         "较 $tol=10^{-2}$ 下降 $%.0f\\times$" % v2s["max_ratio"],
         "残差在 $tol\\le %s$ 处触底" % tol_tex,
         "触底值为机器精度，继续收紧容差无改善"),
        ("V3",
         "阴影半径的像素映射（闭式 $f_{\\rm px}\\tan\\psi_{\\rm sh}$）",
         "$R_{\\rm px}$ 亚像素反解",
         sci(v3sub, 2),
         "亚像素 $<10^{-9}$；整数扫描 $<1$\\,px",
         "扫描口径的 %.2f\\%% 偏差是像素量化，非物理误差"
         % (100.0 * v3scan)),
        ("V4a",
         "屏幕纵坐标 $\\to$ 冲击参数 $b$ 的闭式",
         "$b_{\\rm tracer}=%.8f$" % v4a[-1]["b_tracer"],
         sci(abs(v4a[-1]["rel_b"]), 2),
         "$<10^{-12}$",
         "几何映射与着色器实现逐位一致"),
        ("V4b",
         "FIDO 角半径 "
         "$\\sin\\psi=(3\\sqrt{3}M/r_{0})$ $\\sqrt{1-2M/r_{0}}$",
         "$r_{0}=4M$：$\\psi=%.3f^{\\circ}$" % b4["psi_deg"],
         rel(b4["err_flat"]),
         "FIDO 口径为准；flat/chart 均为近似",
         "同一行 chart 口径 %s；$r_{0}\\ge26M$ 后两口径误差才降到 "
         "$5\\%%$ 内" % rel(b4["err_chart"])),
        ("V5",
         "逃逸半径处的出射方向重建",
         "$\\max=%.4f$\\,px @ $1000\\times600$" % v5max,
         "--",
         "$<0.05$\\,px",
         "误差随 $b$ 单调增长；$R_{\\rm esc}=140M$ 在此视场下足够"),
        ("V6",
         "渐进累积收敛（$n=1\\to1024$，逐位重复）",
         "rms 降 $%.2f$ 倍，$\\propto n^{-%.2f}$" % (drop, k_rms),
         "--",
         "8-bit 亮度地板 $=0$；三块重复对逐位相同",
         "窗口内高频残余：r2 降 $%.1f\\%%$，post 降 $%.1f\\%%$"
         % (hf_drop, hf_drop_p)),
        ("V6",
         "幂等性对照（$\\Delta\\equiv0$）",
         "重复对最大差异 $%.1f$" % rep_max,
         "$0$",
         "同一配置重复渲染须逐位相同",
         "冻结抖动时 rms $\\equiv0$：这是幂等性校验，不是精度校验"),
    ]

    w("t16_verify_summary.tex", [" & ".join(r) + " \\\\" for r in rows],
      "六项验证实验的汇总。``对照量'' 一栏给出该项所对照的闭式解或参考实现，"
      "``偏差'' 一栏为实测值与参照值之差（相对量以百分数或科学计数法给出）。"
      "判据一栏是本文采用的验收标准：几何量须在双精度舍入水平内与闭式一致，"
      "渲染量须在亚像素内一致，管线量须在量化台阶内不可区分。"
      "末列为相应的物理或数值说明；全部数值由 "
      "\\protect\\path{validate_pytrace.json} 与 "
      "\\protect\\path{validate_accum.json} "
      "经 \\protect\\path{tools/make_tables.py} 生成。",
      "tab:v6summary", 6,
      ["\\#", "对照量", "关键实测", "偏差", "判据", "备注"],
      size="\\scriptsize",
      align="l p{0.18\\linewidth} p{0.15\\linewidth} p{0.09\\linewidth} "
            "p{0.17\\linewidth} p{0.20\\linewidth}")


def t_subpixel_probe():
    """Table of the *in-app* sub-pixel shadow probe (experiment V3, engineering layer).

    The numbers come from ``probe_measured.json``, which is produced by
    ``paper/tools/measure_probe.py`` driving the shipped application in a
    headless browser -- i.e. the very same ``window.__bh.measure()`` call the
    "measure" button makes.  Nothing here is typed in by hand.
    """
    d = jload("probe_measured.json")
    n = d["samples"]
    sigma = d["sigmaPx"]
    body = []
    for r in d["rows"]:
        resid = r["measured"] - r["analytic"]
        body.append("%d$\\times$%d & %d & %.4f & %.4f & %+.4f & %+.3f & %.1f \\\\"
                    % (r["width"], r["height"], n,
                       r["measured"], r["analytic"],
                       resid, r["rel"], resid / sigma))
    w("t17_subpixel_probe.tex", body,
      "V3（工程层）：运行中的应用内建阴影探针。探针用 $N_{\\rm p}=%d$ 个"
      "分层子像素样本把二值捕获掩膜变成逐像素覆盖率，"
      "再在中央行上反解亚像素边缘（式~\\eqref{eq:subpix}）。"
      "``残差'' 为实测减闭式，``残差$/\\sigma$'' 一栏把它除以覆盖率量化带 "
      "$\\sigma_{\\rm px}=1/(2\\sqrt{2}N_{\\rm p})=%.5f$\\,px。"
      "三点的残差都不超过 $3\\sigma_{\\rm px}$，即全部落在覆盖率量化的"
      "离散格之内；相对误差 $\\le0.034\\%%$。"
      "数据由 \\texttt{paper/tools/measure\\_probe.py} 采集。" % (n, sigma),
      "tab:v3b", 7,
      ["视口", "$N_{\\rm p}$", "实测 [px]", "闭式 [px]",
       "残差 [px]", "相对 [\\%]", "残差$/\\sigma$"],
      size="\\small",
      align="rr r r r r r")


# --------------------------------------------------------------------------- #
def t_r0_scan():
    """Observer-distance scan of the traced shadow radius (shipped app).

    The data come from ``r0_scan.json``, written by ``tools/verify.py`` while it
    drives the real application: for each observer radius ``r0`` the in-app
    probe ``window.__bh.measure()`` locates the bright/dark boundary on the
    central row with its sub-pixel coverage estimator, and the closed form of
    Eq.~\eqref{eq:shadowpx} is evaluated for the same camera state.  Nothing is
    typed in by hand.
    """
    d = jload("r0_scan.json")
    body = []
    for r in d["rows"]:
        # ``measured`` and ``analytic`` are already pixel radii, so their
        # difference is the pixel residual directly - no angular rescaling.
        body.append("%.0f & %.2f & %.2f & %+.3f & %+.2f \\\\"
                    % (r["r0"], r["measured"], r["analytic"], r["rel"],
                       r["measured"] - r["analytic"]))
    w("t18_r0_scan.tex", body,
      "观测者距离扫描：在运行的应用里把相机半径从 $8M$ 推到 $150M$，"
      "每一档都用内建探针反解阴影半径并与式~\\eqref{eq:shadowpx} 的闭式比较"
      "（窗口 $%d\\times%d$、$\\tan\\psi$ 视场 $58^\\circ$、$\\mathtt{autoQuality}$ 关闭、"
      "单帧冻结）。闭式在几何单位下为 $R_{\\rm px}=f_{\\rm px}\\tan\\psi_{\\rm sh}$，"
      "只依赖 $r_0/M$；实测相对偏差在 $\\pm0.13\\%%$ 以内，绝对残差 "
      "$\\le0.11$\\,px。覆盖三个数量级的 $r_0$ 上残差都保持在百分之几个像素，"
      "说明限制这一测量的是覆盖率量化带 $\\sigma_{\\rm px}=0.0147$\\,px "
      "与掩膜本身亚像素级的系统项，而不是阴影角半径的闭式。"
      "数据由 \\texttt{tools/verify.py} 采集（GPU：%s）。"
      % (d["width"], d["height"], d.get("gpu", "n/a").replace("_", "\\_")),
      "tab:r0scan", 5,
      ["$r_0/M$", "实测 [px]", "闭式 [px]", "相对 [\\%]", "残差 [px]"],
      size="\\small",
      align="rrrrr")


# --------------------------------------------------------------------------- #
def t_packaged_ui():
    """Viewport-centring probe taken from the *packaged* executable.

    The numbers come from ``work/portable/ui_probe.py``, which attaches to a
    running ``BlackHoleSimulator.exe`` over CDP and reads the same
    ``window.__bh.measure()`` that the V3/V5 experiments use.  A copy of the
    record lives in ``tools/packaged_ui.json`` because ``work/`` is not shipped.
    """
    d = jload("packaged_ui.json")
    st = d["states"]
    rows = [
        ("open", "侧栏展开"),
        ("collapsed", "侧栏收起（全屏预览）"),
        ("key_f", "\\texttt{F} 键全屏"),
        ("key_h", "\\texttt{H} 键切换预览"),
        ("escape", "\\texttt{Escape} 还原侧栏"),
    ]
    body = []
    for key, label in rows:
        r = st[key]
        body.append(
            "%s & $%d\\times%d$ & %d & %d & $%+.*f$ & %.4f & %.3f & %.3f \\\\"
            % (label, r["css"][0], r["css"][1], r["cssLeft"],
               1 if r["panelCollapsed"] else 0,
               3, r["centreOffsetPx"], r["shadowPx"],
               r["radiusBuf"], r["analyticBuf"]))
    sb = st["scrollbar"]
    w("t19_packaged_ui.tex", body,
      "打包版可执行文件中实测的视口中心不变量（$5$ 种状态）。"
      "画布尺寸为 CSS 像素，$x_{\\rm css}$ 是画布左边缘；"
      "$\\Delta_{\\rm c}$ 为 \\texttt{measureShadow()} 反解的阴影圆心"
      "相对画布几何中心的偏差（渲染缓冲像素）；"
      "$R_{\\rm css}$ 是换算到 CSS 像素的阴影半径——五种状态下"
      "\\emph{逐位相同}；$R_{\\rm buf}$/$R_{\\rm ana}$ 为当前缓冲分帧下的"
      "实测半径与该帧解析值，两者之差即 $\\Delta_{\\rm c}$ 之外的"
      "第二项亚像素校验。探针量化带宽 "
      "$\\sigma_{\\rm px}=1/(2\\sqrt2\\cdot24)=0.0147$\\,px。"
      "测量环境：\\texttt{%s}；便携包 SHA256 \\texttt{%s}$\\ldots$。"
      "同一次探针还回读了侧栏滚动条的样式："
      "\\texttt{scrollbarWidth=%s}、\\texttt{scrollbarColor=%s}、"
      "\\texttt{scrollbarGutter=%s}，"
      "\\texttt{::-webkit-scrollbar} 规则 %d 条。"
      % (d["gpu"].replace("_", "\\_"), d["exe_zip_sha256"][:16],
         sb["scrollbarWidth"], sb["scrollbarColor"], sb["scrollbarGutter"],
         sb["webkitRules"]),
      "tab:ui-probe", 8,
      ["状态", "画布 [px]", "$x_{\\rm css}$", "收起",
       "$\\Delta_{\\rm c}$ [px]", "$R_{\\rm css}$ [px]",
       "$R_{\\rm buf}$", "$R_{\\rm ana}$"],
      size="\\footnotesize",
      align="lrrrrrrr")


# --------------------------------------------------------------------------- #
def main() -> int:
    os.makedirs(OUT, exist_ok=True)
    t_validate()
    t_disk()
    t_perf()
    t_defaults()
    t_presets()
    t_integrator()
    t_verify_summary()
    t_subpixel_probe()
    t_r0_scan()
    t_packaged_ui()
    print("[tbl] all tables written to", OUT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
